-- ============================================================
-- Orijins POS -- Manual Inventory Schema
-- ============================================================
-- NOTE: This file is now DEPRECATED.
-- All manual inventory tables (manual_inventory_items,
-- manual_inventory_sheets, manual_inventory_entries) and their
-- seed data are fully included in the main schema.sql file.
--
-- Run ONLY schema.sql for a fresh deployment. Do NOT run this file.
-- ============================================================
